### ISSUE TITLE
Redirect from plantatlas.brc.ac.uk has broken

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/bsbi-atlas-drupal8#10]
The redirect from https://plantatlas.brc.ac.uk/ to https://atlasredirect.bsbi.org/ appears to have broken. The old brc pages are now failing to resolve instead of redirecting.

i.e.
https://plantatlas.brc.ac.uk/plant/viscum-album should go to https://atlasredirect.bsbi.org/plant/viscum-album (the user will be further redirected to https://plantatlas2020.org/atlas/2cd4p9h.cpe)

https://plantatlas.brc.ac.uk/ should got to https://atlasredirect.bsbi.org/ (from which the user will be redirected to https://plantatlas2020.org/ )

@BirenRathod could you have a look at this please.

**Comment by BirenRathod** [comment]
@japonicus it does redirecting if I type this url plantatlas.brc.ac.uk and press enter but if I copy and paste this https://plantatlas.brc.ac.uk, it doesn't do anything. it seems like it is overwriting url like this -> https://[plantatlas.brc.ac.uk](https://plantatlas.brc.ac.uk/)/

**Comment by japonicus** [comment]
Thanks, has the server stopped listening on port 443? I'm sure this used to work for both http and https.

**Comment by BirenRathod** [comment]
@japonicus It is not a problem with port 443 but somewhere in the redirection at your end or my end.

**Comment by BirenRathod** [comment]
@japonicus not sure, you have noticed by now but I have assigned the SSL certificate, so Port 443 is active again.

**Comment by BirenRathod** [comment]
@japonicus Just to let you know that the redirection has broken by https://atlasredirect.bsbi.org/. Nothing at my end suggests not working.

**Comment by japonicus** [comment]
@BirenRathod thanks very much for highlighting this. I moved to a new server and somehow the configuration for this was broken. It's working again now.
