### ISSUE TITLE
Limited view in taxon dropdown

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/bsbi-atlas-drupal8#14]
From an email from Ian Park: 

"I have found that when searching for a particularly long genus with many species, there is no slider button to 'scroll down' the sidebar i.e. the list simply runs off the bottom of the page. I haven't been able to find a way to access some genera in this way without knowing the name of the exact species I am looking for. "

**Comment by japonicus** [comment]
I wonder what the use-case for a longer or comprehensive Atlas taxon list is for website users. I don't really understand the need.

It should be straightforward to provide a full taxon list download in the way that you suggest, but I'm concerned that people may misinterpret the significance of the list.

Inclusion of a taxon in the list would have not particular meaning beyond 'this is a taxon that the editors chose to map'. The list would not be a complete snap-shot of taxa present in the wild etc., nor a list of the 'concepts BSBI cares about recording'.

**Comment by tangiblegains** [comment]
It seems like a tricky issue to fix, but I too don't think it's appropriate to have a separate tab with the full list of taxa mapped. One fairly unsatisfactory answer for the user might be to input the genus, scroll down to the bottom of the list of 20 (on the rare? occasions when the list exceeds 20), and then simply type in succeeding letters of the alphabet for the species name, until they find what they are looking for. Or they could use one of countless wildflower guides to search for the species name!

**Comment by sacrevert** [comment]
Closing, as this seems to be a non-issue. If one is doing some sort of vague search, forgetting the specific epithet and wanting a reminder, then they could just do something like "Carex a...", "Carex b..." or whatever until they find it. The site is not really intended as an aide-memoire in this way
