### ISSUE TITLE
Gallery overlaps taxon selector on Android phone

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/bsbi-atlas-drupal8#15]
![Screenshot_20230912-112552](https://github.com/BiologicalRecordsCentre/bsbi-atlas-drupal8/assets/5985134/d113a4b7-d40f-45d2-9720-7a49968691ab)

Can someone check on iPhone?

**Comment by burkmarr** [comment]
It's a problem on all platforms I think. I think also that I can fix it.
