### ISSUE TITLE
Add selected country to attribution text of trend plot downloads

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/bsbi-atlas-drupal8#17]
From @sacrevert: "is it possible to add the selected country to the trend plot downloads, perhaps in the attribution text?"

**Comment by burkmarr** [comment]
@sacrevert - this is now addressed on https://dev-brc-plantatlas9.pantheonsite.io/.

**Comment by sacrevert** [comment]
Sorry, don't know why I thought it was already doing this, but I see it isn't: can we add the short-term/long-term info to the plots too please?

**Comment by sacrevert** [comment]
I just remembered that of course figs 1-3 already show dates, so it wasn't needed. I forgot that fig 4 lacks that context however. Perhaps you can reopen this, or create a new issue, as you like. No rush at all for this of course

**Comment by burkmarr** [comment]
I want to fix https://github.com/BiologicalRecordsCentre/bsbi-atlas-drupal8/issues/18, so I'll tackle this at the same time.

**Comment by burkmarr** [comment]
@sacrevert - just to avoid any toing and froing, can you specify the text to add to figure four. (I don't know if the words 'short-term' and 'long-term' are enough or if you want to specify dates.)

**Comment by burkmarr** [comment]
@sacrevert - another question. I've just realised that figure 3 doesn't show dates either, so presumably treat this the same way is figure 4?

**Comment by sacrevert** [comment]
Yes, I realised that too. I think just apply the text to all trend figures to simplify solution. "short-term"/"long-term", however phrased, is fine. For example, "Data is for long-term trend, Scotland." etc
