### ISSUE TITLE
Other dropdowns can interfere with taxon selector 

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/bsbi-atlas-drupal8#19]
@burkmarr e.g. 
![Screenshot_20231009-144412](https://github.com/BiologicalRecordsCentre/bsbi-atlas-drupal8/assets/5985134/e72cb6e8-acc6-41ce-b04d-d7a05f10f42d)

**Comment by burkmarr** [comment]
Fixed on live.

**Comment by burkmarr** [comment]
Previous 'fix' caused issue #20, so a different solution is required.

**Comment by burkmarr** [comment]
Fixed again and pushed to live.
