### ISSUE TITLE
Dropdown interference 

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/bsbi-atlas-drupal8#20]
This actually seems to be a widespread issue @burkmarr 
E.g.
![Screenshot_20231010-125358](https://github.com/BiologicalRecordsCentre/bsbi-atlas-drupal8/assets/5985134/cb2836ec-7cec-4da4-ad7a-bbb20fd20c1d)

**Comment by burkmarr** [comment]
Okay I've reverted the fix to #19 which caused this issue, so I will close this issue and reopen #19.
