### ISSUE TITLE
Apparency/latitude plot scaling options do not work on Android phone

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/bsbi-atlas-drupal8#21]
@burkmarr 
I can't screenshot this as the plot and various scaling options don't on the screen at the same time, but when I choose the different scaling options for the apparency/latitude plot, the plot itself does not update on my phone. I tested it for the same species on my laptop, and it works fine there. (Also, the same type of functionality on the Trends tab works fine on my phone, so seems specific to the apparency/latitude plot).

**Comment by burkmarr** [comment]
@sacrevert - thanks for spotting. From the code this bug must have been present since first deployed. It was evident on any display where the controls are displayed under the charts. I've fixed it now.
