### ISSUE TITLE
Cotula sessilis (Soliva pteropserma) caption missing

### ISSUE THREAD

**Issue by kwal2** [BiologicalRecordsCentre/bsbi-atlas-drupal8#26]
We have maps, phenology, alts for this but the caption is missing

**Comment by burkmarr** [comment]
Relevant comments from emails (to keep all info in one place:

@japonicus: "Do you know whether caption text for Cotula sessilis was ever written and has got lost? There is no caption for this (or its synonyms) in the DDb."

@kwal2: "I can't remember writing the caption for Soliva although I remember editing Capsella rubra to take account of Colin Pope and Paul Stanley's article in BSBI News that first alerted us to the presence of Cotula sessilis on Caravan sites. I'm happy to write a caption for it as it has similarities with C. alpina that I have worked on so shouldn't take too long but just checking we're all happy for this to be uploaded it if I did that?"

**Comment by kwal2** [comment]
I've now written the account for Cotula sessilis on the DDb so it can be imported to the website when me make changes

**Comment by sacrevert** [comment]
@japonicus & @kwal2 to arrange export of update to @burkmarr

**Comment by sacrevert** [comment]
@burkmarr Do you think we should just be closing these once they are confirmed as updated in DDb? This one seems like it could be closed on that basis

**Comment by burkmarr** [comment]
@sacrevert - I suggest we leave them open until I have a caption update from the DDB, then I go through them and close them once I confirm they have been addressed.

**Comment by sacrevert** [comment]
@burkmarr I was thinking of creating a general issue relating to the overall process of providing you with the update. We also need to catalogue to changes for an errata, so, I was thinking that we can just looked back at closed issues for that (assuming that all changes are catalogued here). Thoughts @kwal2 @japonicus ?

**Comment by sacrevert** [comment]
I must have forgotten this discussion, as I have been leaving issues open that affect book (for errata) and closing those that only affect website (on assumption that they would be automatically fixed on production of a new export). Given that's what I've been doing, I suggest we close this.
