### ISSUE TITLE
Stachys alpina status

### ISSUE THREAD

**Issue by kwal2** [BiologicalRecordsCentre/bsbi-atlas-drupal8#30]
The map for Stachys alpina https://plantatlas2020.org/atlas/2cd4p9h.82q shows only non-native dots but we have given its national status as native. I think this is because all populations are treated as introductions so maybe we should note that in the text otherwise it lloks like a mistake

**Comment by sacrevert** [comment]
Status is given as "Native or alien in Britain" online -- does this differ in the book?  I would suggest that this is fine, and that the suggested changes are after-the-fact editorialising, not an erratum. I suggest closing this.
