### ISSUE TITLE
New dataset bullet for homepage

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/bsbi-atlas-drupal8#35]
Now that I am starting to put the data on Zenodo, can we add a new bullet to front page of the website please @burkmarr , under "Links to other _Plant Atlas 2020_ outputs:"

The bullet is as follows:
- All of the data required to reproduce the maps and figures presented in the book and website are available via Zenodo ([this search](https://zenodo.org/communities/plantatlas2020/records?q=&l=list&p=1&s=10&sort=newest) will display all _Plant Atlas 2020_ datasets on that platform).

**Comment by burkmarr** [comment]
That page update is done.

**Comment by sacrevert** [comment]
@burkmarr Thanks Rich!
Sorry to be fussy, but can you italicise "Plant Atlas 2020", just so that it is the same as the other bullets? Many thanks :)

**Comment by burkmarr** [comment]
Done.
