### ISSUE TITLE
Viola lactea - wrong images on website

### ISSUE THREAD

**Issue by tangiblegains** [BiologicalRecordsCentre/bsbi-atlas-drupal8#37]
As the title suggest, images on the website are not of V. lactea. Photos need to be removed, and ideally a pukka new image uploaded as a replacement,

**Comment by tangiblegains** [comment]
Images deleted in the DDb

**Comment by sacrevert** [comment]
@tangiblegains to close 

For species lacking images, can we export a list and share it somewhere? @japonicus @burkmarr

**Comment by burkmarr** [comment]
@sacrevert - here is a CSV indicating the taxa that have no images:
[atlas_taxa_2023-02-22-1605 - no images.csv](https://github.com/BiologicalRecordsCentre/bsbi-atlas-drupal8/files/15467189/atlas_taxa_2023-02-22-1605.-.no.images.csv)
