### ISSUE TITLE
Poa nemoralis photo

### ISSUE THREAD

**Issue by kwal2** [BiologicalRecordsCentre/bsbi-atlas-drupal8#39]
Photo for Poa nemoralis in the gallery is Milium effusum

**Comment by sacrevert** [comment]
My understanding is that all photos are on a BSBI website and the Atlas just uses the DDb ID to call them up. If something like this is true, then I assume all photo issues can be dealt with by BSBI staff, and then changes will automatically flow to Atlas @burkmarr @japonicus ?

This is not to say that they shouldn't be posted here, they can be, but then the resolution, and issue closing, should be with BSBI folk

**Comment by japonicus** [comment]
Images are served from BSBI's server, but are referenced by individually by URL in the taxon metadata used for the atlas, so a change requires an update in the DDb and re-export of the taxon details (or a manual change to the atlas descriptors).

**Comment by sacrevert** [comment]
Ok, so @tangiblegains or @kwal2 can update on BSBI server for these cases and then close these issues. We can do a new export or relevant details for Atlas website at the same time as captions/other errors to be fixed.

Do @tangiblegains and @kwal2 know how to add/edit photos on BSBI server?

**Comment by tangiblegains** [comment]
Photo of Poa nemoralis deleted in DDb

**Comment by tangiblegains** [comment]
Yep, I can delete/add photos in the DDb. I'll do that for all the photo
issues.


Dr Peter Stroh
Scientific Officer
Botanical Society of Britain and Ireland (BSBI)
Cambridge University Botanic Garden
1 Brookside
Cambridge CB2 1JE

email: ***@***.***
tel: 01223 762054 or 07981 572678

**Comment by sacrevert** [comment]
@tangiblegains cheers, can you close? I don't have permission

**Comment by tangiblegains** [comment]
Yes, but don't want to close until I look through my photo archive to try
and find replacement pics.


Dr Peter Stroh
Scientific Officer
Botanical Society of Britain and Ireland (BSBI)
Cambridge University Botanic Garden
1 Brookside
Cambridge CB2 1JE

email: ***@***.***
tel: 01223 762054 or 07981 572678

**Comment by sacrevert** [comment]
I'm closing this and opening a new issue related to general photo management linking to Rich's CSV. We actually have a lot of issues with photos, and I don't think it particularly useful to have some of them represented by GitHub issues and others being dealt with elsewhere -- there are, after all, presumably tens of species for which we could add photos.
