### ISSUE TITLE
Authorities italicised in atlas page citations

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/bsbi-atlas-drupal8#4]
Very minor, but, if possibe, it would be nice to unitalicise species' authorities in the page citation texts, and in the citation reference manager tagging

**Comment by burkmarr** [comment]
@sacrevert - I've updated the code for formatting the page citation text, the citation on a downloaded map and the metadata tags for the reference managers. In the limited testing of the latter that's available to me, the citation managers seem to ignore any html formatting within the metadata tags. I've implemented on the test site but not yet pushed to live.

https://test-brc-plantatlas9.pantheonsite.io/

Take a look and if you are happy with it I will push to live.

**Comment by sacrevert** [comment]
Thanks Rich. It's better in terms of presentation on the website, and in terms of the "copy HTML" tagging, but in Zotero the "span class" markup appears in the bibliography in Word. I know you said that this is difficult given that there is no single refman standard to rule them all, so I am tempted to ignore this, and let people manually edit their reference lists after auto-generation. So, happy for it to go live, unless you want to spend extra time fiddling!

**Comment by burkmarr** [comment]
I might be able to fix that fairly simply Oli. I'll take a look before pushing to live.

**Comment by burkmarr** [comment]
That should be fixed now I think @sacrevert. If you'd like to take another look at test and if all okay, I will push to live.

**Comment by sacrevert** [comment]
This is what it looks like in Word with Zotero now, all italics. Again, not a massive problem (people can edit), so, up to you whether you persevere or not!
![image](https://user-images.githubusercontent.com/5985134/227185109-db6a85d6-fefa-4cdd-9496-d0e3628997cc.png)

**Comment by burkmarr** [comment]
Does it look okay from test @sacrevert?

**Comment by sacrevert** [comment]
Looks great, only issue I can see is that markup is appearing on page title in browser tab:
![image](https://user-images.githubusercontent.com/5985134/227190230-ca61593b-f057-4d9b-a35c-22f673461628.png)

**Comment by burkmarr** [comment]
Yes (see https://github.com/BiologicalRecordsCentre/bsbi-atlas-drupal8/issues/4#issuecomment-1480988898). I've just pushed a change to test that fixes that. Can you check that zotero has retained it's formatting? (There's a chance that it may be getting it from the title tag that the citation_title meta tag).

**Comment by sacrevert** [comment]
Looks fine to me (see below), and it presented correctly in Word too.

![image](https://user-images.githubusercontent.com/5985134/227192178-c2da7270-96f2-4c5f-8e95-8f1b60e6b3f7.png)

**Comment by burkmarr** [comment]
Okay it's live now.
