### ISSUE TITLE
Some old BSBI Atlas links not redirecting

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/bsbi-atlas-drupal8#7]
Seems to be that any old link that is just a pointer to an occurrence within one of the pages that just listed taxa alphabetically on the old site is not being redirected. For example:
https://plantatlas.brc.ac.uk/finder/plant/%20?page=169

**Comment by japonicus** [comment]
At present that url (/finder) isn't being redirected to my server so is outside the scope of my lookup shim.

Even if it was redirected, at present I don't know how page numbers relate to taxa. I suspect that information may have been lost permanently when the old Atlas site was taken down. 

A partial solution would be to redirect all 'finder' pages to the atlas homepage.

**Comment by sacrevert** [comment]
Thanks @japonicus , I think the redirect all finder pages to the new homepage solution would be fine.

**Comment by sacrevert** [comment]
This appears to be fixed now
