### ISSUE TITLE
Logos not displaying on atlas pages on Android device

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/bsbi-atlas-drupal8#8]
![Screenshot_20230418-093841](https://user-images.githubusercontent.com/5985134/232722424-59f25661-e4a3-48cc-b50b-e06f9408e022.png)

**Comment by burkmarr** [comment]
It's not just Android. It's happening on Chrome on Windows too (and probably all other platforms). Might be due to some Drupal updates (which happened a week ago). I will take a look today.

**Comment by burkmarr** [comment]
Some weird stuff going on here @sacrevert - I just cleared the cache on my browser and it worked. Then I cleared the drupal cache and checked on my Android mobile - that worked too. Can you re-check your phone?

**Comment by sacrevert** [comment]
Seems ok now, both before and after clearing cache
